### ISSUE TITLE
Is there anyone more detailed launch introduction? I am very like this project

### ISSUE THREAD

**Issue by boboChina** [mysql-time-machine/replicator#1]
RT

**Comment by bdevetak** [comment]
Hi,

We have documentation and user guide at: https://mysql-time-machine.github.io/
It is a work in progress, but should be enough to get you started.

Regards,
Bosko.

**Comment by boboChina** [comment]
Recommend to you a good open source project:
https://github.com/alibaba/otter.
Hope to be useful to you.
