### ISSUE TITLE
Null column conflicts with string with value "NULL"

### ISSUE THREAD

**Issue by TvdW** [mysql-time-machine/replicator#16]
In [Converter.java](https://github.com/mysql-time-machine/replicator/blob/master/src/main/java/com/booking/replication/schema/column/types/Converter.java#L155) there's code to return the string "NULL" when the value is null. This was a tradeoff needed for HBase, but problematic with Kafka where we can just write a proper null value: in a string column a reader is unable to distinguish the word NULL from a NULL value.

**Comment by bdevetak** [comment]
Thanks for reporting this Tom. This does make sense. We need to keep the "NULL" option for HBase, but we can make null-value-handling a configurable option, so that for other appliers like Kafka,  Converter can return the JSON null value instead of "NULL" string.

**Comment by bdevetak** [comment]
This issue is now fixed with release 0.14.4
