### ISSUE TITLE
Replicator sends *update* time not *commit* time - meaning statements can be processed out of order chronologically.

### ISSUE THREAD

**Issue by demerphq** [mysql-time-machine/replicator#6]
Talking with Bosko at my desk.

For the purpose of monitoring it is essential that we can process data by the *commit* time of the change. In particular this means that if we see an update for time T+1 we must be able to assume safely that there will be no more data for time T.

This is particularly important for a scenario like this:

begin work;
insert into T (when_it_happened) values (NOW());
select sleep(30);
commit;

the current logic will show the time of the *update*, which is 30 seconds before the time of the commit. Nobody should have been able to see that update until it is committed.

This may mean that the entire streaming principal needs to be reconsidered (hopefully not!) - however this is essential for any for "real time" processing, and in particular in association with the new epoch features in kafka.

Currently it is NOT possible to build a (sane) monitor on top of this stream. (Of course it has many other uses!)

Yves

**Comment by bdevetak** [comment]
Closing the issue - resolved by pull request #7. Now all data events have timestamp that corresponds to the transaction commit time.
